---

- name: 'Run playbook-bootstrap_python.yml'
  ansible.builtin.import_playbook: playbook-bootstrap_python.yml

- name: 'Run playbook-install_k3s.yml'
  ansible.builtin.import_playbook: playbook-install_k3s.yml

- name: 'Run playbook-bookstack_installation.yml'
  ansible.builtin.import_playbook: playbook-bookstack_installation.yml
